#!/usr/bin/env bash


DEPLOYER_SRV_DIR=/srv


# this function makes path to be a empty directory (clean content or create directory)
dp::ensure_empty_dir() {
  target="$1"
  # lesson written in blood
  # if $service_dir unset, following rm command will remove '/*'
  if [ ! -n "$target" ]; then return 1; fi

  if [ -d "$target" ]; then
    rm -rf "$target"/* "$target"/.*
  elif [ -f "$target" ]; then
    mv "$target" "$target.bak"
    mkdir -p "$target"
  else
    mkdir -p "$target"
  fi
}

# this function sync conents in a directory to another
dp::sync() {
  source="$1"
  target="$2"

  dp::ensure_empty_dir "$target"
  cp -r "$source/." "$target"
}

dp::randname() {
  echo "deployer-$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 16 | head -n 1)"
}

dp::github_latest_version() {
  curl --silent "https://api.github.com/repos/$1/releases/latest" |
    grep '"tag_name":' |
    sed -E 's/.*"([^"]+)".*/\1/'
}

dp::pull_github_archive() {
  project=$1
  project_name=$(echo "$project" | sed -E 's|.+/||')
  target=$2

  project_version=$(dp::github_latest_version "$project")

  tmp_dir="/tmp/$(dp::randname)"

  archive_file="$tmp_dir/$project_version.tar.gz"

  mkdir -p "$tmp_dir"
  wget -q -O "$archive_file" "https://github.com/$project/archive/$project_version.tar.gz"

  tar -xzf "$archive_file" -C "$tmp_dir"

  archive_path="$tmp_dir/$project_name-$(echo "$project_version" | sed -E 's/v//')"

  dp::clear_gitkeep "$archive_path"

  dp::sync "$archive_path" "$target"

  rm -r "$tmp_dir"
}

dp::pull_github_project() {
  project=$1
  target=$2
  
  dp::ensure_empty_dir "$target"

  git clone -b master --single-branch --depth=1 "https://github.com/$project.git" "$target"

  dp::clear_gitkeep "$target"
}

dp::clear_gitkeep() {
  target=$1
  find "$target" -name ".gitkeep" -exec rm -rf '{}' +
}

dp::is_config_loaded() {
  if [ "$current_project" ]; then return 0; fi
  return 1
}

dp::load_service_conf() {
  project=$1

  if [ "$current_project" = "$project" ]; then return 0; fi

  source <(wget -qO- "https://raw.githubusercontent.com/$project/master/.deployer/deployer.conf")
  # DEPLOYER_SERVICE_GROUP=<string>
  # DEPLOYER_SERVICE_NAME=<string>
  # DEPLOYER_TYPE=<github_repo|github_archive>
  # DEPLOYER_SECRET=<null|true>
  # DEPLOYER_DATA=<null|true>
  # DEPLOYER_BEFORE_UPDATE=<command>
  # DEPLOYER_AFTER_UPDATE=<command>
  # DEPLOYER_SERVICE_UP=<command>

  export service_group=${DEPLOYER_SERVICE_GROUP:-others}
  export service_name=$DEPLOYER_SERVICE_NAME

  deploy_dist="$DEPLOYER_SRV_DIR/$service_group"
  backups_dir="$deploy_dist/.backups"

  export service_dir="$deploy_dist/$service_name"

  export secrets_src="$deploy_dist/$service_name/secrets"
  export secrets_dir="$deploy_dist/$service_name.secrets"
  export secrets_bak="$backups_dir/$service_name.secrets"

  export data_src="$deploy_dist/$service_name/data"
  export data_dir="$deploy_dist/$service_name.data"
  export data_bak="$backups_dir/$service_name.data"

  export current_project=$project
}


dp::backup-data() {
  mkdir -p "$backups_dir"
  backup_file="$data_bak-$(date '+%y%m%d%H%M%S').zip"
  zip -rq "$backup_file" "$data_dir"
}

# initialize data directory
dp::init-data() {
  # if data dir already exist, backup it and then remove
  if [ -d "$data_dir" ]; then
    docker run --rm -it -v "$data_dir:/data" alpine:3.8 chown -R "$UID:$GID" /data
    dp::backup-data
    echo "$data_dir will be removed, you can find the backup in $backups_dir"
  fi

  dp::sync "$data_src" "$data_dir"
}

dp::backup-secrets() {
  mkdir -p "$backups_dir"
  backup_dir="$secrets_bak-$(date '+%y%m%d%H%M%S')"
  dp::sync "$secrets_dir" "$backup_dir"
}

# initialize secret directory
dp::init-secrets() {
  # if secrets dir already exist, backup it and then remove
  if [ -d "$secrets_dir" ]; then
    dp::backup-secrets
    echo "$secrets_dir will be removed, you can find the backup in $backups_dir"
  fi

  dp::sync "$secrets_src" "$secrets_dir"
  hash tree && {
    echo
    echo "Configure these files before you up the service:"
    echo "================================================"
    tree "$secrets_dir"
    echo "================================================"
  }
}

dp::update() {
  if [ "$DEPLOYER_BEFORE_UPDATE" ]; then $DEPLOYER_BEFORE_UPDATE; fi

  # update to latest code
  case "$DEPLOYER_TYPE" in
    github_repo)    dp::pull_github_project "$current_project" "$service_dir" ;;
    github_archive) dp::pull_github_archive "$current_project" "$service_dir" ;;
    *) echo "DEPLOYER_TYPE error: $DEPLOYER_TYPE"; exit 1 ;;
  esac

  if [ "$DEPLOYER_AFTER_UPDATE" ]; then $DEPLOYER_AFTER_UPDATE; fi

  if [ "$DEPLOYER_DATA" = "true" ] && [ ! -d "$data_dir" ]; then
    dp::init-data
  fi

  if [ "$DEPLOYER_SECRET" = "true" ] && [ ! -d "$secrets_dir" ]; then
    dp::init-secrets
  fi
}

dp::up() {
  pushd "$service_dir"

  if [ -f "./.env.template" ]; then
    envsubst < "./.env.template" > ".env"
  fi

  if [ -f "./docker-compose.yml" ] || [ -f "./docker-compose.yaml" ]; then
    docker-compose up -d
  fi

  if [ "$DEPLOYER_SERVICE_UP" ]; then
    $DEPLOYER_SERVICE_UP
  fi

  popd
}


dp::usage() {
  tee << END
Usage: $0 [command] project_name
$0 deploy service for geektheripper

Examples:
  $0 update foo/bar           # Update service to latest or pull the service
  $0 up foo/bar               # Start the service
  $0 init-secrets foo/bar     # initialize secrets directory (remove if existed)
  $0 init-data foo/bar        # initialize data directory (remove if existed)
  $0 backup-secrets foo/bar   # backup secrets directory
  $0 backup-data foo/bar      # backup data directory

Don't forget configure secrets files before up your service
END
}

action=$1
project=$2

if [ -z "$action" ] || [ -z "$project" ]; then
  dp::usage
  exit 1
fi

dp::load_service_conf "$project"

case "$action" in
  update) dp::update ;;
  up) dp::up ;;
  init-secrets) dp::init-secrets ;;
  init-data) dp::init-data ;;
  backup-secrets) dp::backup-secrets ;;
  backup-data) dp::backup-data ;;
  *) dp::usage ;;
esac
